/* ============================================================================
   create_incremental_staging.sql
   Idempotent setup for the SQL INCREMENTAL LOADING layer.

   Creates schema [stg] and three objects (all isolated from the existing
   warehouse dbo.* tables, which this layer never alters):

     stg.fact_transactions_stage   transient landing for ONE Silver batch
     stg.fact_transactions_reject  quarantine for rows that fail validation
     stg.incremental_load_log      per-batch audit log (drives idempotency)

   Safe to re-run: every object is guarded by an existence check.
   Run by load_silver_incremental_to_sql.py, or by hand:
     sqlcmd -S ahmed\SQLEXPRESS -E -C -d fintech_db -i create_incremental_staging.sql
   ============================================================================ */
-- REQUIRED before the filtered unique index below: filtered indexes (and DML on
-- tables that carry them) demand these options ON. pyodbc defaults them ON, but
-- sqlcmd defaults QUOTED_IDENTIFIER OFF -- so set them explicitly to make this
-- script work from ANY client.
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET NOCOUNT ON;

-- CREATE SCHEMA must be the first statement in its batch; wrapping it in EXEC
-- sidesteps that rule so this whole file can run as a single batch (pyodbc).
IF SCHEMA_ID('stg') IS NULL EXEC('CREATE SCHEMA stg');

-- ----------------------------------------------------------------------------
-- Staging: a TRANSIENT copy of one Silver batch. Mirrors the fact's business
-- columns exactly (so the MERGE needs no implicit casts) but EXCLUDES
-- transaction_sk (that surrogate key is generated by the warehouse IDENTITY).
-- Two lineage columns are kept for auditability: silver_batch_id (which batch)
-- and _silver_processed_at_utc (when Silver produced the row). Truncated and
-- reloaded every run, so columns are nullable -- validation enforces the rules.
-- ----------------------------------------------------------------------------
IF OBJECT_ID('stg.fact_transactions_stage','U') IS NULL
    CREATE TABLE stg.fact_transactions_stage (
        date_key                INT             NULL,
        time_key                INT             NULL,
        account_key             INT             NULL,
        peer_account_key        INT             NULL,
        transaction_type_key    INT             NULL,
        decline_reason_key      INT             NULL,
        merchant_key            INT             NULL,
        transaction_id          VARCHAR(50)     NULL,
        mc_transaction_id       VARCHAR(50)     NULL,
        ach_transfer_id         VARCHAR(50)     NULL,
        amount_minor            BIGINT          NULL,
        amount_egp              DECIMAL(18,2)   NULL,
        abs_amount_egp          DECIMAL(18,2)   NULL,
        fx_amount_minor         BIGINT          NULL,
        exchange_rate_e6        BIGINT          NULL,
        is_outbound             BIT             NULL,
        is_declined             BIT             NULL,
        is_fx                   BIT             NULL,
        silver_batch_id         VARCHAR(50)     NULL,
        _silver_processed_at_utc VARCHAR(40)    NULL
    );

-- Speeds up the per-batch validation/MERGE source scan.
IF OBJECT_ID('stg.fact_transactions_stage','U') IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_stage_batch')
    CREATE INDEX IX_stage_batch
        ON stg.fact_transactions_stage (silver_batch_id) INCLUDE (transaction_id);

-- ----------------------------------------------------------------------------
-- Rejects: rows that fail validation are QUARANTINED here, never dropped, so
-- bad data stays auditable and replayable (same philosophy as Silver quarantine).
-- ----------------------------------------------------------------------------
IF OBJECT_ID('stg.fact_transactions_reject','U') IS NULL
    CREATE TABLE stg.fact_transactions_reject (
        reject_id               BIGINT          IDENTITY(1,1) NOT NULL,
        date_key                INT             NULL,
        time_key                INT             NULL,
        account_key             INT             NULL,
        peer_account_key        INT             NULL,
        transaction_type_key    INT             NULL,
        decline_reason_key      INT             NULL,
        merchant_key            INT             NULL,
        transaction_id          VARCHAR(50)     NULL,
        mc_transaction_id       VARCHAR(50)     NULL,
        ach_transfer_id         VARCHAR(50)     NULL,
        amount_minor            BIGINT          NULL,
        amount_egp              DECIMAL(18,2)   NULL,
        abs_amount_egp          DECIMAL(18,2)   NULL,
        fx_amount_minor         BIGINT          NULL,
        exchange_rate_e6        BIGINT          NULL,
        is_outbound             BIT             NULL,
        is_declined             BIT             NULL,
        is_fx                   BIT             NULL,
        silver_batch_id         VARCHAR(50)     NULL,
        _silver_processed_at_utc VARCHAR(40)    NULL,
        reject_reason           VARCHAR(100)    NOT NULL,
        rejected_at_utc         DATETIME2(3)    NOT NULL DEFAULT SYSUTCDATETIME(),
        CONSTRAINT PK_fact_transactions_reject PRIMARY KEY (reject_id)
    );

-- ----------------------------------------------------------------------------
-- Load audit log: ONE row per (batch, attempt). This is the SQL-side equivalent
-- of the Silver offset checkpoint: a batch that already has a SUCCESS row is
-- never reprocessed. FAILED attempts are also recorded (for retry/audit).
-- ----------------------------------------------------------------------------
IF OBJECT_ID('stg.incremental_load_log','U') IS NULL
    CREATE TABLE stg.incremental_load_log (
        log_id          BIGINT          IDENTITY(1,1) NOT NULL,
        silver_batch_id VARCHAR(50)     NOT NULL,
        status          VARCHAR(20)     NOT NULL,        -- 'SUCCESS' | 'FAILED'
        rows_staged     INT             NULL,
        rows_valid      INT             NULL,
        rows_inserted   INT             NULL,
        rows_updated    INT             NULL,
        rows_rejected   INT             NULL,
        started_at_utc  DATETIME2(3)    NULL,
        finished_at_utc DATETIME2(3)    NULL,
        duration_ms     INT             NULL,
        error_message   NVARCHAR(4000)  NULL,
        CONSTRAINT PK_incremental_load_log PRIMARY KEY (log_id)
    );

-- Hard idempotency guard: a batch can be marked SUCCESS at most once. A second
-- successful load of the same batch would violate this filtered unique index.
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UX_incr_log_success_batch')
    CREATE UNIQUE INDEX UX_incr_log_success_batch
        ON stg.incremental_load_log (silver_batch_id)
        WHERE status = 'SUCCESS';
